config/routes.rb
Rails.application.routes.draw do

  get '/reservations/:id/payment_method' => "payments#payment_method", as: :payment_method
  post '/reservations/:id/decision' => "payments#decision"
  get '/users/:id/payments/deposit' => "payments#deposit", as: :deposit
  post '/users/:id/payments/new' => "payments#new", as: :payment
  post '/users/:id/payments/create' => "payments#create"

  get '/users/:id/reservations' => "reservations#your_reservation", as: :your_reservation

  root 'welcome#index'

  resources :listings do
    resources :reservations, only: [:new, :create]
  end

  resources :reservations, only: [:show]

  resources :notices

  resources :events

  resources :users, only: [:show, :edit, :update, :index]

  get '/search' => 'listings#search'

  post 'events/:id/attend' => 'event_attendees#attend', as: 'attend'
  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # mailbox folder routes
  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

  # conversations
  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  get "/users/:id/conversations/new" => 'conversations#new_private_message', as: 'new_private_message'
  # post "/users/:id/conversations" => 'conversations#create_private_message', as: 'private_message'

  resources :topics do
    resources :comments
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :topic
  belongs_to :user

  default_scope {order(created_at: :desc)}

end

app/models/confirmation.rb
class Confirmation < ActiveRecord::Base
	belongs_to :reservation

	def self.pay_by_cash(reservation_id)
		record = Confirmation.find_by(reservation_id: reservation_id)
		Confirmation.update(record.id, method: "Cash")
	end

	def self.pay_by_credit(reservation_id)
		record = Confirmation.find_by(reservation_id: reservation_id)
		Confirmation.update(record.id, method: "Credit")
	end

	def self.send_cash_payment_message(reservation_id)
		reservation = Reservation.find(reservation_id)
		purchaser_id = reservation.user_id
		seller_id = reservation.listing.user_id
		purchaser = User.find(purchaser_id)
		seller = User.find(seller_id)
		purchaser.send_message(seller, "I will be paying by Cash.", "Cash payment choice by #{purchaser}.")
	end

end

app/models/credit.rb
class Credit < ActiveRecord::Base
	belongs_to :user

	# def credit_balance?
	# 	if Credit.find_by(user_id: self.id).nil?
	# 		return "0.00"
	# 	else
	# 		record = Credit.find_by(user_id: self.id)
	# 		amount = record.amount
	# 		cents = record.cents
	# 		return "#{amount}.#{cents}"
	# 	end
	# end

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user
  has_many :event_attendees
  default_scope {order(created_at: :desc)}

end

app/models/event_attendee.rb
class EventAttendee < ActiveRecord::Base
  belongs_to :user
  belongs_to :event
end

app/models/forum.rb
class Forum < ActiveRecord::Base

end

app/models/listing.rb
class Listing < ActiveRecord::Base
	has_many :reservations

  belongs_to :user
  belongs_to :listing_type

  scope :listing_type_id, -> (listing_type_id) { where listing_type_id: listing_type_id }

end

app/models/listing_type.rb
class ListingType < ActiveRecord::Base
  has_many :listings
end

app/models/notice.rb
class Notice < ActiveRecord::Base

  default_scope {order(created_at: :desc)}

end

app/models/payment.rb
class Payment < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
 
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
	has_many :confirmations
	belongs_to :listing
  belongs_to :user

	default_scope {order(created_at: :desc)}

end

app/models/topic.rb
class Topic < ActiveRecord::Base
	belongs_to :user
	has_many :comments, :dependent => :destroy

	default_scope {order(created_at: :desc)}
end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User
  has_many :events_attendees
  has_many :topics
  has_many :comments
  has_many :credits
  has_many :events
  has_many :listings
  has_many :reservations
  mount_uploader :photo, PhotoUploader
  # require 'mailboxer'
  # include Mailboxer::Models::Messageable
  extend Mailboxer::Models::Messageable::ActiveRecordExtension

  acts_as_messageable

  def mailboxer_name
    self.email
  end

  def mailboxer_email(object)
    nil
  end

  def credit_balance?
    if Credit.find_by(user_id: self.id).nil?
      return "0.00"
    else
      record = Credit.find_by(user_id: self.id)
      amount = record.amount
      cents = record.cents
      return "#{amount}.#{cents}"
    end
  end

  enum role: [:resident, :administrator, :super_admin]

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  def index
    @listings = Listing.all
    @listing_types = ListingType.pluck(:name)
  end

  def search
    @listings = Listing.where(nil)
    search = search_params(params)

    if !search[:listing_type_id].blank?
      search[:listing_type_id] = ListingType.find_by_name(search[:listing_type_id]).id
    end

    search.each do |key, value|
      @listings = @listings.public_send(key, value) if value.present?
    end

    @listing_types = ListingType.pluck(:name)

    if @listings.empty?
      flash[:alert] = "No record found. Please search again."
    end

    render 'listings/index'
  end

  def new
    @listing = Listing.new
    @listing_types = ListingType.pluck(:name)
  end

  def create
    price = listing_params[:price].split(".")
    if price[1].nil?
      @price = listing_params[:price] << ".00"
      @listing = current_user.listings.new(text: listing_params[:text], price: @price, listing_type_id: ListingType.find_by_name(listing_params[:listing_type_id]).id)
      if @listing.save
        redirect_to @listing
      else
        flash[:alert] = "Your listing can't be saved."
        @listing = Listing.new
        @listing_types = ListingType.pluck(:name)
        render 'new'
      end
    elsif price[1].length == 1
      flash.now[:alert] = "There is only 1 decimal. Please input price again."
      @listing = Listing.new
      @listing_types = ListingType.pluck(:name)
      render "new"
    elsif price[1].length == 0
      @price = listing_params[:price] << "00"
      @listing = current_user.listings.new(text: listing_params[:text], price: @price, listing_type_id: ListingType.find_by_name(listing_params[:listing_type_id]).id)
      if @listing.save
        redirect_to @listing
      else
        flash[:alert] = "Your listing can't be saved."
        @listing_types = ListingType.pluck(:name)
        render 'new'
      end
    elsif price[1].length > 2
      flash.now[:alert] = "There are more than 2 decimals. Please input price again."
      @listing = Listing.new
      @listing_types = ListingType.pluck(:name)
      render "new"
    else
      @price = listing_params[:price]
      @listing = current_user.listings.new(text: listing_params[:text], price: @price, listing_type_id: ListingType.find_by_name(listing_params[:listing_type_id]).id)
      if @listing.save
        redirect_to @listing
        else
        flash[:alert] = "Your listing can't be saved."
        render 'new'
      end
    end
  end

  def show
    @listing = Listing.find(params[:id])
  end

  private
  def listing_params
    params.require(:listing).permit(:text, :listing_type_id, :price)
  end

  def search_params(params)
    params.slice(:listing_type_id, :min_price, :max_price)
  end
end

app/helpers/credits_helper.rb
module CreditsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/mailbox_helper.rb
module MailboxHelper
  def unread_messages_count
    # how to get the number of unread messages for the current user
    # using mailboxer
    mailbox.inbox(:unread => true).count(:id, :distinct => true)
  end
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/listings/_form.html.erb
<%= form_for @listing do |f| %>
  <div class="form-group">
    <%= f.label :text%>
    <%= f.text_field :text, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :listing_type_id %>
    <%= f.select :listing_type_id, options_for_select(@listing_types), {}, {class: 'form-control'} %>
  </div>

  <div class="form-group">
    <%= f.label :price %>
    <%= f.number_field :price, class: 'form-control', min: '0.01', step: '0.01', placeholder: '0.00' %>
  </div>

  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/listings/index.html.erb
<div class="jumbotron text-center" id="listings_index">
  <h1>Marketplace</h1><br><br><br><br>
</div><br>

<div class="row">
  <div class="col-md-12">
    <%= link_to "Create new listing", new_listing_path, class: "btn btn-success btn-block"  %><br>
  </div>
</div>

<div class="row">
  <div class="search">
    <div class="col-md-12">
        <%= form_tag("/search", method: "get", class: 'form-inline') do %>
          <div class="col-md-3">
            <div class="form-group">
              <%= label_tag :listing_type_id %>
              <%= select_tag :listing_type_id, options_for_select(@listing_types), class: 'form-control', include_blank: true %>
            </div>
          </div>

          <div class="col-md-3">
            <div class="form-group">
              <%= label_tag :min_price %>
              <%= number_field_tag :min_price, class: 'form-control' %>
            </div>
          </div>

          <div class="col-md-3">
            <div class="form-group">
              <%= label_tag :max_price %>
              <%= number_field_tag :max_price, class: 'form-control' %>
            </div>
          </div>

          <div class="col-md-3">
            <%= submit_tag "Search", class: "btn btn-info btn-block" %>
          </div>
        <% end %>
    </div>
  </div>
</div>

<% @listings.each do |listing| %>
  <div class="col-md-4 col-sm-6 col-xs-6 col-xxs-12 listing-item">
    <%= link_to listing_path(listing) do %>
      <% if listing.listing_type.name == 'Carpark' %>
        <%= image_tag "carpark.jpg", class: "img-responsive" %>
      <% elsif listing.listing_type.name == 'Food' %>
        <%= image_tag "food.jpg", class: "img-responsive" %>
      <% elsif listing.listing_type.name == 'Furniture' %>
        <%= image_tag "furniture.png", class: "img-responsive" %>
      <% end %>
      <!-- <img src="images/work_1.jpg" alt="Free HTML5 Website Template by FreeHTML5.co" class="img-responsive"> -->
      <h3 class="fh5co-work-title"><%= listing.text %></h3>

    <% end %>

    <div class="row">
      <div class="col-md-12">
        <p>Category: <%= listing.listing_type.name %> <%= link_to "Buy Now", new_listing_reservation_path(listing), class: 'pull-right btn btn-warning' %></p>
      </div>
      <div class="col-md-12">
        <p>
          Price: RM <%= listing.price %>
        </p>
      </div>
    </div>
  </div>
<% end %>

app/views/listings/new.html.erb
<h1>New Listing</h1>
<%= render 'form'%> <br><hr> 
<div> <%= link_to 'Back to Listings', listings_path, class: "btn btn-default" %></div>

app/views/listings/show.html.erb
<div class="row">
  <div class="col-md-12">
  <%= link_to 'Back', listings_path, class: 'btn btn-default' %>
  </div>

  <div class="col-md-12 text-center">
    <h1><%= @listing.text %></h1> by <%= link_to @listing.user.name, user_path(@listing.user) %>
    <hr>
  </div>

  <div class="col-md-12">
    <p class="text-center">Category: <%= @listing.listing_type.name %></p>
    <% if @listing.listing_type.name == 'Carpark' %>
      <%= image_tag "carpark.jpg", class: "img-responsive center-block", size: '450x300' %><br>
    <% elsif @listing.listing_type.name == 'Food' %>
      <%= image_tag "food.jpg", class: "img-responsive center-block", size: '450x300' %><br>
    <% elsif @listing.listing_type.name == 'Furniture' %>
      <%= image_tag "furniture.png", class: "img-responsive center-block", size: '450x300' %><br>
    <% end %>
  </div>


  <div class="col-md-offset-4 col-md-4">
    <p>Price: RM <%= @listing.price %> <%= link_to "Buy Now", new_listing_reservation_path(@listing), class: 'pull-right btn btn-warning' %></p>
  </div>
</div>