config/routes.rb
Rails.application.routes.draw do

  get '/reservations/:id/payment_method' => "payments#payment_method", as: :payment_method
  post '/reservations/:id/decision' => "payments#decision"
  get '/users/:id/payments/deposit' => "payments#deposit", as: :deposit
  post '/users/:id/payments/new' => "payments#new", as: :payment
  post '/users/:id/payments/create' => "payments#create"

  get '/users/:id/reservations' => "reservations#your_reservation", as: :your_reservation

  root 'welcome#index'

  resources :listings do
    resources :reservations, only: [:new, :create]
  end

  resources :reservations, only: [:show]

  resources :notices

  resources :events

  resources :users, only: [:show, :edit, :update, :index]

  get '/search' => 'listings#search'

  post 'events/:id/attend' => 'event_attendees#attend', as: 'attend'
  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # mailbox folder routes
  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

  # conversations
  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  get "/users/:id/conversations/new" => 'conversations#new_private_message', as: 'new_private_message'
  # post "/users/:id/conversations" => 'conversations#create_private_message', as: 'private_message'

  resources :topics do
    resources :comments
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :topic
  belongs_to :user

  default_scope {order(created_at: :desc)}

end

app/models/confirmation.rb
class Confirmation < ActiveRecord::Base
	belongs_to :reservation

	def self.pay_by_cash(reservation_id)
		record = Confirmation.find_by(reservation_id: reservation_id)
		Confirmation.update(record.id, method: "Cash")
	end

	def self.pay_by_credit(reservation_id)
		record = Confirmation.find_by(reservation_id: reservation_id)
		Confirmation.update(record.id, method: "Credit")
	end

	def self.send_cash_payment_message(reservation_id)
		reservation = Reservation.find(reservation_id)
		purchaser_id = reservation.user_id
		seller_id = reservation.listing.user_id
		purchaser = User.find(purchaser_id)
		seller = User.find(seller_id)
		purchaser.send_message(seller, "I will be paying by Cash.", "Cash payment choice by #{purchaser}.")
	end

end

app/models/credit.rb
class Credit < ActiveRecord::Base
	belongs_to :user

	# def credit_balance?
	# 	if Credit.find_by(user_id: self.id).nil?
	# 		return "0.00"
	# 	else
	# 		record = Credit.find_by(user_id: self.id)
	# 		amount = record.amount
	# 		cents = record.cents
	# 		return "#{amount}.#{cents}"
	# 	end
	# end

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user
  has_many :event_attendees
  default_scope {order(created_at: :desc)}

end

app/models/event_attendee.rb
class EventAttendee < ActiveRecord::Base
  belongs_to :user
  belongs_to :event
end

app/models/forum.rb
class Forum < ActiveRecord::Base

end

app/models/listing.rb
class Listing < ActiveRecord::Base
	has_many :reservations

  belongs_to :user
  belongs_to :listing_type

  scope :listing_type_id, -> (listing_type_id) { where listing_type_id: listing_type_id }

end

app/models/listing_type.rb
class ListingType < ActiveRecord::Base
  has_many :listings
end

app/models/notice.rb
class Notice < ActiveRecord::Base

  default_scope {order(created_at: :desc)}

end

app/models/payment.rb
class Payment < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
 
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
	has_many :confirmations
	belongs_to :listing
  belongs_to :user

	default_scope {order(created_at: :desc)}

end

app/models/topic.rb
class Topic < ActiveRecord::Base
	belongs_to :user
	has_many :comments, :dependent => :destroy

	default_scope {order(created_at: :desc)}
end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User
  has_many :events_attendees
  has_many :topics
  has_many :comments
  has_many :credits
  has_many :events
  has_many :listings
  has_many :reservations
  mount_uploader :photo, PhotoUploader
  # require 'mailboxer'
  # include Mailboxer::Models::Messageable
  extend Mailboxer::Models::Messageable::ActiveRecordExtension

  acts_as_messageable

  def mailboxer_name
    self.email
  end

  def mailboxer_email(object)
    nil
  end

  def credit_balance?
    if Credit.find_by(user_id: self.id).nil?
      return "0.00"
    else
      record = Credit.find_by(user_id: self.id)
      amount = record.amount
      cents = record.cents
      return "#{amount}.#{cents}"
    end
  end

  enum role: [:resident, :administrator, :super_admin]

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :require_login

  def new
  end

  def create
    recipients = User.where(id: conversation_params[:recipients])
    conversation = current_user.send_message(recipients, conversation_params[:body], conversation_params[:subject]).conversation

    if conversation
      flash[:notice] = "Your message was successfully sent!"
      redirect_to conversation_path(conversation)
    else
      flash[:alert] = "Your message can't be sent."
      render 'new'
    end
  end

  def new_private_message
    @chosen_recipient = User.find(params[:id])
    render 'conversations/new_private_message'
  end

  # def create_private_message
  #   recipient = User.find(params[:id])
  #   conversation = current_user.send_message(recipient, conversation_params[:body], conversation_params[:subject]).conversation

  #   if conversation
  #     flash[:notice] = "Your message was successfully sent!"
  #     redirect_to conversation_path(conversation)
  #   else
  #     flash[:alert] = "Your message can't be sent"
  #     render 'new'
  #   end
  # end

  def show
    @receipts = conversation.receipts_for(current_user)
    # mark conversation as read
    conversation.mark_as_read(current_user)
  end

  def reply
    current_user.reply_to_conversation(conversation, message_params[:body])
    flash[:notice] = "Your reply message was successfully sent!"
    redirect_to conversation_path(conversation)
  end

  def trash
    conversation.move_to_trash(current_user)
    redirect_to mailbox_inbox_path
  end

  def untrash
    conversation.untrash(current_user)
    redirect_to mailbox_inbox_path
  end

  private

  def conversation_params
    params.require(:conversation).permit(:subject, :body,recipients:[])
  end

  def message_params
    params.require(:message).permit(:body, :subject)
  end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/credits_helper.rb
module CreditsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/conversations/_conversation.html.erb
<div class="media">
  <div class="media-left">
    <%= link_to user_path(conversation.originator) do %>
      <% if conversation.originator.photo.file.nil? %>
        <%= image_tag("avatar_placeholder.png", size: '64x64', class: 'media-object')%>
      <% else %>
      <%= image_tag(conversation.originator.photo.url.to_s, size: "64x64", class: "media-object") %>
      <% end %>
    <% end %>
      <!-- user avators can go here -->
  </div>
  <div class="media-body">
    <h4 class="media-heading">
      <%= conversation.originator.name %> <br> <!-- change to originator.name in future -->
      <small><b>Subject: </b><%= conversation.subject %></small><br>
      <small><b>Date: </b><%=  conversation.messages.last.created_at.strftime("%A, %b %d, %Y at %I:%M%p") %></small>
    </h4>
    <%= truncate conversation.messages.last.body, length: 145 %>
    <%= link_to "View", conversation_path(conversation)  %>
  </div>
</div>

app/views/conversations/_form.html.erb
<%= form_for :conversation, url: :conversations, html: { class: "" } do |f| %>
    <div class="form-group">
      <%= f.label :recipients %>
      <%= f.select(:recipients, User.all.collect {|p| [ p.name, p.id ] }, {}, { multiple: true , class: "form-control" })%> <!-- change p.email to p.name in future -->
    </div>
    <div class="form-group">
      <%= f.label :subject %>
      <%= f.text_field :subject, placeholder: "Subject", class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :message %>
      <%= f.text_area :body, class: 'form-control',placeholder: "Type your message here", rows: 4  %>
    </div>

    <%= f.submit "Send Message", class: "btn btn-success" %>

<% end %>

app/views/conversations/_messages.html.erb
<% @receipts.each do |receipt| %>
  <% message = receipt.message %>
  <div class="media">
    <div class="media-left">
      <%= link_to user_path(message.sender) do %>
        <% if message.sender.photo.file.nil? %>
          <%= image_tag("avatar_placeholder.png", size: '64x64', class: 'media-object')%>
        <% else %>
          <%= image_tag(message.sender.photo.url.to_s, size: "64x64", class: "media-object") %>
        <% end %>
      <% end %>
      <!-- user avators can go here -->
    </div>
    <div class="media-body">
      <h4 class="media-heading">
        <%= message.sender.name %> <br> <!-- change to message.sender.name in future -->
        <small><b>Subject: </b><%= message.subject %></small><br>
        <small><b>Date: </b><%=  message.created_at.strftime("%A, %b %d, %Y at %I:%M%p") %></small>
      </h4>
      <%= message.body %>
    </div>
  </div>
<% end %>

app/views/conversations/_private_message_form.html.erb
<%= form_for :conversation, url: :conversations, html: { class: "" } do |f| %>
    <div class="form-group">
      <%= f.label :recipients, "Recipient" %>
      <%= f.select(:recipients, [[@chosen_recipient.name, @chosen_recipient.id]], {}, { multiple: true , class: "form-control" })%> <!-- change p.email to p.name in future -->
    </div>
    <div class="form-group">
      <%= f.label :subject %>
      <%= f.text_field :subject, placeholder: "Subject", class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :message %>
      <%= f.text_area :body, class: 'form-control',placeholder: "Type your message here", rows: 4  %>
    </div>

    <%= f.submit "Send Message", class: "btn btn-success" %>

<% end %>

app/views/conversations/new.html.erb
<%= render partial: 'mailbox/folder_view', locals: { is_conversation: true } %>

app/views/conversations/new_private_message.html.erb
<%= render partial: 'mailbox/private_message_folder_view', locals: { is_conversation: true } %>

app/views/conversations/show.html.erb
<div class="row">
  <div class="spacer"></div>
  <div class="col-md-6">
    <%= link_to "Compose", new_conversation_path, class: "btn btn-success" %>
  </div>
  <div class="col-md-6 text-right">
    <% if conversation.is_trashed?(current_user) %>
        <%= link_to 'Untrash', untrash_conversation_path(conversation), class: 'btn btn-info', method: :post %>
    <% else %>
        <%= link_to 'Move to trash', trash_conversation_path(conversation), class: 'btn btn-danger', method: :post,
                    data: {confirm: 'Are you sure?'} %>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="spacer"></div>
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= render 'mailbox/folders' %>
      </div>
    </div>
  </div>

  <div class="col-md-8">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= render partial: 'messages' %>
      </div>
      <div class="panel-footer">
        <!-- Reply Form -->
        <%= form_for :message, url: reply_conversation_path(conversation) do |f| %>
            <div class="form-group">
              <%= f.text_area :body, placeholder: "Reply Message", rows: 4, class: "form-control" %>
            </div>
            <%= f.submit "Reply", class: 'btn btn-danger pull-right' %>
        <% end %>
        <div class="clearfix"></div>
      </div>
    </div>
  </div>

</div>