config/routes.rb
Rails.application.routes.draw do

  get '/reservations/:id/payment_method' => "payments#payment_method", as: :payment_method
  post '/reservations/:id/decision' => "payments#decision"
  get '/users/:id/payments/deposit' => "payments#deposit", as: :deposit
  post '/users/:id/payments/new' => "payments#new", as: :payment
  post '/users/:id/payments/create' => "payments#create"

  get '/users/:id/reservations' => "reservations#your_reservation", as: :your_reservation

  root 'welcome#index'

  resources :listings do
    resources :reservations, only: [:new, :create]
  end

  resources :reservations, only: [:show]

  resources :notices

  resources :events

  resources :users, only: [:show, :edit, :update, :index]

  get '/search' => 'listings#search'

  post 'events/:id/attend' => 'event_attendees#attend', as: 'attend'
  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # mailbox folder routes
  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

  # conversations
  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  get "/users/:id/conversations/new" => 'conversations#new_private_message', as: 'new_private_message'
  # post "/users/:id/conversations" => 'conversations#create_private_message', as: 'private_message'

  resources :topics do
    resources :comments
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :topic
  belongs_to :user

  default_scope {order(created_at: :desc)}

end

app/models/confirmation.rb
class Confirmation < ActiveRecord::Base
	belongs_to :reservation

	def self.pay_by_cash(reservation_id)
		record = Confirmation.find_by(reservation_id: reservation_id)
		Confirmation.update(record.id, method: "Cash")
	end

	def self.pay_by_credit(reservation_id)
		record = Confirmation.find_by(reservation_id: reservation_id)
		Confirmation.update(record.id, method: "Credit")
	end

	def self.send_cash_payment_message(reservation_id)
		reservation = Reservation.find(reservation_id)
		purchaser_id = reservation.user_id
		seller_id = reservation.listing.user_id
		purchaser = User.find(purchaser_id)
		seller = User.find(seller_id)
		purchaser.send_message(seller, "I will be paying by Cash.", "Cash payment choice by #{purchaser}.")
	end

end

app/models/credit.rb
class Credit < ActiveRecord::Base
	belongs_to :user

	# def credit_balance?
	# 	if Credit.find_by(user_id: self.id).nil?
	# 		return "0.00"
	# 	else
	# 		record = Credit.find_by(user_id: self.id)
	# 		amount = record.amount
	# 		cents = record.cents
	# 		return "#{amount}.#{cents}"
	# 	end
	# end

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user
  has_many :event_attendees
  default_scope {order(created_at: :desc)}

end

app/models/event_attendee.rb
class EventAttendee < ActiveRecord::Base
  belongs_to :user
  belongs_to :event
end

app/models/forum.rb
class Forum < ActiveRecord::Base

end

app/models/listing.rb
class Listing < ActiveRecord::Base
	has_many :reservations

  belongs_to :user
  belongs_to :listing_type

  scope :listing_type_id, -> (listing_type_id) { where listing_type_id: listing_type_id }

end

app/models/listing_type.rb
class ListingType < ActiveRecord::Base
  has_many :listings
end

app/models/notice.rb
class Notice < ActiveRecord::Base

  default_scope {order(created_at: :desc)}

end

app/models/payment.rb
class Payment < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
 
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
	has_many :confirmations
	belongs_to :listing
  belongs_to :user

	default_scope {order(created_at: :desc)}

end

app/models/topic.rb
class Topic < ActiveRecord::Base
	belongs_to :user
	has_many :comments, :dependent => :destroy

	default_scope {order(created_at: :desc)}
end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User
  has_many :events_attendees
  has_many :topics
  has_many :comments
  has_many :credits
  has_many :events
  has_many :listings
  has_many :reservations
  mount_uploader :photo, PhotoUploader
  # require 'mailboxer'
  # include Mailboxer::Models::Messageable
  extend Mailboxer::Models::Messageable::ActiveRecordExtension

  acts_as_messageable

  def mailboxer_name
    self.email
  end

  def mailboxer_email(object)
    nil
  end

  def credit_balance?
    if Credit.find_by(user_id: self.id).nil?
      return "0.00"
    else
      record = Credit.find_by(user_id: self.id)
      amount = record.amount
      cents = record.cents
      return "#{amount}.#{cents}"
    end
  end

  enum role: [:resident, :administrator, :super_admin]

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @events = Event.all.limit(3)
    @notices = Notice.all.limit(3)
    @topics = Topic.all.limit(3)
  end
end

app/helpers/credits_helper.rb
module CreditsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<% if signed_in? %>
  <div class="jumbotron text-center" id="home2">
    <h1 class="cozyco">CozyCo</h1>
    <p>Welcome to <span class="cozyco">CozyCo</span>, <%= current_user.name %></p><br><br><br><br><br>
  </div><br>


<div class="row">
  <div class="col-sm-4">
    <div class="panel panel-success">
      <div class="panel-heading"><h4>Latest Notices</h4></div>
        <div class="panel-body">
          <% @notices.each do |notice| %>
            <b><span class="glyphicon glyphicon-pushpin"></span> <%= notice.title %> </b><br>
            <p> <%= notice.body %> </p>
            <%= link_to 'More details...', notice_path(notice) %><hr>
          <% end %>
          <%= link_to 'All Notices', notices_path %>
        </div>
    </div>
</div>

<div class="col-sm-4">
  <div class="panel panel-info">
    <div class="panel-heading"><h4>Upcoming Events</h4></div>
      <div class="panel-body">
        <% if !@events.blank? %>
        <% @events.each do |event| %>
        <b><%= event.title %></b><br>
        <p><%= event.body %><p>
        <p> <span class="glyphicon glyphicon-calendar"></span> <%= event.start_date.strftime("%m/%d/%Y")%>
            <span class="glyphicon glyphicon-user"></span> <%= event.event_attendees.where(attending: true).count %> </p>

              <%= link_to 'More details...', event_path(event) %><hr>
        <% end %>
        <% end %>
        <%= link_to 'All Events', events_path %>
      </div>
  </div>
</div>

<div class="col-sm-4">
    <div class="panel panel-warning">
      <div class="panel-heading"><h4>Forum</h4></div>
        <div class="panel-body">
          <% if !@topics.blank? %>
          <% @topics.each do |topic| %>
          <b><%= topic.name %></b><br>
          <p><span class="glyphicon glyphicon-comment"></span> <%= topic.comments.count%> comments<p>
            <%= link_to 'View forum...', topic_path(topic) %><hr>
            <% end %>
            <% end %>

          <%= link_to 'All Topics', topics_path %>
        </div>
    </div>
  </div>
</div>

<% else %>
<div class="jumbotron text-center" id="home1">
  <h1 class="cozyco">CozyCo</h1>
</div>
<% end %>