config/routes.rb
Rails.application.routes.draw do

  get '/reservations/:id/payment_method' => "payments#payment_method", as: :payment_method
  post '/reservations/:id/decision' => "payments#decision"
  get '/users/:id/payments/deposit' => "payments#deposit", as: :deposit
  post '/users/:id/payments/new' => "payments#new", as: :payment
  post '/users/:id/payments/create' => "payments#create"

  get '/users/:id/reservations' => "reservations#your_reservation", as: :your_reservation

  root 'welcome#index'

  resources :listings do
    resources :reservations, only: [:new, :create]
  end

  resources :reservations, only: [:show]

  resources :notices

  resources :events

  resources :users, only: [:show, :edit, :update, :index]

  get '/search' => 'listings#search'

  post 'events/:id/attend' => 'event_attendees#attend', as: 'attend'
  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # mailbox folder routes
  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

  # conversations
  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  get "/users/:id/conversations/new" => 'conversations#new_private_message', as: 'new_private_message'
  # post "/users/:id/conversations" => 'conversations#create_private_message', as: 'private_message'

  resources :topics do
    resources :comments
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :topic
  belongs_to :user

  default_scope {order(created_at: :desc)}

end

app/models/confirmation.rb
class Confirmation < ActiveRecord::Base
	belongs_to :reservation

	def self.pay_by_cash(reservation_id)
		record = Confirmation.find_by(reservation_id: reservation_id)
		Confirmation.update(record.id, method: "Cash")
	end

	def self.pay_by_credit(reservation_id)
		record = Confirmation.find_by(reservation_id: reservation_id)
		Confirmation.update(record.id, method: "Credit")
	end

	def self.send_cash_payment_message(reservation_id)
		reservation = Reservation.find(reservation_id)
		purchaser_id = reservation.user_id
		seller_id = reservation.listing.user_id
		purchaser = User.find(purchaser_id)
		seller = User.find(seller_id)
		purchaser.send_message(seller, "I will be paying by Cash.", "Cash payment choice by #{purchaser}.")
	end

end

app/models/credit.rb
class Credit < ActiveRecord::Base
	belongs_to :user

	# def credit_balance?
	# 	if Credit.find_by(user_id: self.id).nil?
	# 		return "0.00"
	# 	else
	# 		record = Credit.find_by(user_id: self.id)
	# 		amount = record.amount
	# 		cents = record.cents
	# 		return "#{amount}.#{cents}"
	# 	end
	# end

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user
  has_many :event_attendees
  default_scope {order(created_at: :desc)}

end

app/models/event_attendee.rb
class EventAttendee < ActiveRecord::Base
  belongs_to :user
  belongs_to :event
end

app/models/forum.rb
class Forum < ActiveRecord::Base

end

app/models/listing.rb
class Listing < ActiveRecord::Base
	has_many :reservations

  belongs_to :user
  belongs_to :listing_type

  scope :listing_type_id, -> (listing_type_id) { where listing_type_id: listing_type_id }

end

app/models/listing_type.rb
class ListingType < ActiveRecord::Base
  has_many :listings
end

app/models/notice.rb
class Notice < ActiveRecord::Base

  default_scope {order(created_at: :desc)}

end

app/models/payment.rb
class Payment < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
 
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
	has_many :confirmations
	belongs_to :listing
  belongs_to :user

	default_scope {order(created_at: :desc)}

end

app/models/topic.rb
class Topic < ActiveRecord::Base
	belongs_to :user
	has_many :comments, :dependent => :destroy

	default_scope {order(created_at: :desc)}
end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User
  has_many :events_attendees
  has_many :topics
  has_many :comments
  has_many :credits
  has_many :events
  has_many :listings
  has_many :reservations
  mount_uploader :photo, PhotoUploader
  # require 'mailboxer'
  # include Mailboxer::Models::Messageable
  extend Mailboxer::Models::Messageable::ActiveRecordExtension

  acts_as_messageable

  def mailboxer_name
    self.email
  end

  def mailboxer_email(object)
    nil
  end

  def credit_balance?
    if Credit.find_by(user_id: self.id).nil?
      return "0.00"
    else
      record = Credit.find_by(user_id: self.id)
      amount = record.amount
      cents = record.cents
      return "#{amount}.#{cents}"
    end
  end

  enum role: [:resident, :administrator, :super_admin]

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.events.new(event_params)
    if @event.save
      redirect_to @event
    else
      render 'new'
    end
  end

  def show
    @event = Event.find(params[:id])
    @attend = EventAttendee.where("event_id = ? AND user_id = ?", params[:id], current_user.id).take
    @event_attendees = @event.event_attendees.where(attending: true)
  end

  def edit
    @event = Event.find(params[:id])
    render 'edit'
  end

  def update
    @event = Event.find(params[:id])
     if @event.update!(event_params)
       redirect_to @event
     else
       render 'edit'
     end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to events_path
  end

  def event_params
    params.require(:event).permit(:title, :body, :start_date, :end_date, :start_time, :location, :POC)
  end
end

app/helpers/credits_helper.rb
module CreditsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/helpers/mailbox_helper.rb
module MailboxHelper
  def unread_messages_count
    # how to get the number of unread messages for the current user
    # using mailboxer
    mailbox.inbox(:unread => true).count(:id, :distinct => true)
  end
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<%= form_for event do |f| %>

  <div class="form-group">
    <%= f.label :event %>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :details %>
    <%= f.text_area :body, class: "form-control", rows: 8 %>
  </div>

  <div class="form-group">
    <%= f.label :start_date %>
    <%= f.date_field :start_date, required: true, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :start_time %>
    <%= f.time_field :start_time, required: true, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :end_date %>
    <%= f.date_field :end_date, required: true, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :location %>
    <%= f.text_field :location, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :contact %>
    <%= f.text_field :POC, class: "form-control" %>
  </div>

  <%= f.submit class: "btn btn-primary btn-block" %>
<% end %>

app/views/events/edit.html.erb
<div class="row">
  <div class="col-md-12"><%= link_to 'Back', events_path, class: "btn btn-default" %></div>
  <div class="col-md-12 text-center"><h1>Edit event</h1></div>
</div>

<%= render 'form', :event => @event %>

app/views/events/index.html.erb
<div class="jumbotron text-center" id="events_index">
  <h1>Events</h1><br><br><br><br>
</div><br>

<%= link_to "Create an event", new_event_path, class: "btn btn-success btn-block" %>
<div id="calendar" class="text-center center-block"></div>

app/views/events/new.html.erb
<div><h1>New event</h1></div>

<%= render 'form', :event => @event %><br><hr> 

<div class="col-md-12"> <%= link_to 'Back to Events', events_path, class: "btn btn-default" %></div>

app/views/events/show.html.erb
<!-- Modal -->
<div class="modal fade" id="myModal" role="dialog">
  <div class="modal-dialog modal-sm">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">People attending <%= @event.title %></h4>
      </div>
      <div class="modal-body">
        <% @event_attendees.each do |attendee| %>
          <%= link_to attendee.user.name, user_path(attendee.user) %>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>

<div class="row">
  <div class="col-md-1">
    <%= link_to "Back", events_path, class: "btn btn-default" %>
  </div>
  <div class="col-md-offset-9 col-md-2">
    <%= link_to 'Edit', edit_event_path(@event), class: "btn btn-primary" %>
    <%= link_to 'Delete', event_path(@event), class: "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %>
  </div>
  <div class="col-md-12 text-center">
    <h2><%= @event.title %></h2>
  </div>

  <div class="col-md-12 text-center">
    <b>Created by:</b> <%= link_to @event.user.name, user_path(@event.user) %>
  </div>
</div>

<hr>

<div class="row event-body">
  <div class="col-md-6">
    <div class="row">
      <div class="col-md-12 event-header">
        <i class="fa fa-bars" aria-hidden="true"></i> <b>Details</b>
      </div>
      <div class="col-md-12 text-justify">
        <%= simple_format(@event.body) %>
      </div>
    </div>
  </div>


  <div class="col-md-6">
    <div class="row">
      <div class="col-md-12 event-header">
          <i class="fa fa-map-marker" aria-hidden="true"></i> <b>Location</b>
        </div>
        <div class="col-md-12">
          <%= simple_format(@event.location) %>
        </div>
    </div>

    <div class="row" style="padding-bottom: 10px">
      <div class="col-md-12 event-header">
        <i class="fa fa-bookmark-o" aria-hidden="true"></i> <b>Start Date</b>
      </div>
      <div class="col-md-12">
        <%= @event.start_date %>
      </div>
    </div>

    <div class="row" style="padding-bottom: 10px">
      <div class="col-md-12 event-header">
        <i class="fa fa-clock-o" aria-hidden="true"></i> <b>Time</b>
      </div>
      <div class="col-md-12">
        <%= @event.start_time.strftime("%I:%M%P") %>
      </div>
    </div>

    <div class="row">
      <div class="col-md-12 event-header">
        <i class="fa fa-phone" aria-hidden="true"></i> <b>POC</b>
      </div>
      <div class="col-md-12">
        <%= @event.POC %>
      </div>
    </div>
  </div>
</div>

<hr>

<div class="row">
  <div class="col-md-12 text-center">
    <% if @attend.nil? %>
      <%= link_to "Attend this event", attend_path(@event), method: :post, class: "btn btn-success" %>
    <% elsif @attend.attending %>
      <%= link_to "Unattend this event", attend_path(@event), method: :post, class: "btn btn-danger" %>
    <% else %>
      <%= link_to "Attend this event", attend_path(@event), method: :post, class: "btn btn-success" %>
    <% end %>
  </div>

  <div class="col-md-12 text-center">
    <a href="#myModal" data-toggle="modal" data-dismiss="modal"><%= pluralize(@event_attendees.count, "person") %> attending</a>
  </div>
</div>